# Productiestraat Spaanders B.V.

---
name: Kleine productiestraat

simulationInfo:
  durationInHours: 8760

productionLine:
  name: Kantoortafels
  products:
  - id: 1
    name: normalekantoortafels
    proportion: 2
  - id: 2
    name: luxekantoortafels
    proportion: 1
  machines:

# -------------------- HOUTEN PLATEN (NORMAAL) --------------------

  - id: 1
    name: Zaagmachine (hout)
    configurations:
    - productId: 1
      outputEachMinute: 12
      outputBufferSize: 20
      initializationDurationInSeconds: 6
      turnAroundTimeInSeconds: 16
      meanTimeBetweenFailureInHours: 8800
      meanTimeBetweenFailureStddevInHours: 30
      reparationTimeInMinutes: 24
      previousMachines:
        - machineId: 0
          neededProducts: 1

    - productId: 2
      outputEachMinute: 8
      outputBufferSize: 80
      initializationDurationInSeconds: 9
      turnAroundTimeInSeconds: 21
      meanTimeBetweenFailureInHours: 9800
      meanTimeBetweenFailureStddevInHours: 36
      reparationTimeInMinutes: 27
      previousMachines:
        - machineId: 0
          neededProducts: 1



  - id: 2
    name: Voorboormachine (hout)
    configurations:
    - productId: 1
      outputEachMinute: 12
      outputBufferSize: 20
      initializationDurationInSeconds: 6
      turnAroundTimeInSeconds: 16
      meanTimeBetweenFailureInHours: 8800
      meanTimeBetweenFailureStddevInHours: 30
      reparationTimeInMinutes: 24
      previousMachines:
        - machineId: 1
          neededProducts: 2

    - productId: 2
      outputEachMinute: 8
      outputBufferSize: 10
      initializationDurationInSeconds: 9
      turnAroundTimeInSeconds: 21
      meanTimeBetweenFailureInHours: 9800
      meanTimeBetweenFailureStddevInHours: 36
      reparationTimeInMinutes: 27
      previousMachines:
        - machineId: 1
          neededProducts: 3 
