# Productiestraat Spaanders B.V.

---
name: Kleine productiestraat

simulationInfo:
  durationInHours: 8760

productionLine:
  name: Kantoortafels
  products:
  - id: 1
    name: normalekantoortafels
    proportion: 2
  - id: 2
    name: luxekantoortafels
    proportion: 1
  machines:

# -------------------- HOUTEN PLATEN (NORMAAL) --------------------

  - id: 1
    name: Zaagmachine (hout)
    configurations:
    - productId: 1
      outputEachMinute: 3
      outputBufferSize: 1000
      initializationDurationInSeconds: 600
      turnAroundTimeInSeconds: 16
      meanTimeBetweenFailureInHours: 8800
      meanTimeBetweenFailureStddevInHours: 30
      reparationTimeInMinutes: 24
      previousMachines:
        - machineId: 0 # 0, no previous machine, infinite input
          neededProducts: 1

    - productId: 2
      outputEachMinute: 4
      outputBufferSize: 1000
      initializationDurationInSeconds: 300
      turnAroundTimeInSeconds: 21
      meanTimeBetweenFailureInHours: 9800
      meanTimeBetweenFailureStddevInHours: 36
      reparationTimeInMinutes: 27
      previousMachines:
        - machineId: 0 # 0, no previous machine, infinite input
          neededProducts: 1



  - id: 2
    name: Voorboormachine (hout)
    configurations:
    - productId: 1
      outputEachMinute: 2
      outputBufferSize: 0 # 0, no output buffer size, infinite output
      initializationDurationInSeconds: 500
      turnAroundTimeInSeconds: 16
      meanTimeBetweenFailureInHours: 8800
      meanTimeBetweenFailureStddevInHours: 30
      reparationTimeInMinutes: 24
      previousMachines:
        - machineId: 1
          neededProducts: 2

    - productId: 2
      outputEachMinute: 4
      outputBufferSize: 0 # 0, no output buffer size, infinite output
      initializationDurationInSeconds: 200
      turnAroundTimeInSeconds: 21
      meanTimeBetweenFailureInHours: 9800
      meanTimeBetweenFailureStddevInHours: 36
      reparationTimeInMinutes: 27
      previousMachines:
        - machineId: 1
          neededProducts: 3 
