//
// Created by bas on 15-5-18.
//

#ifndef PRODUCTION_LINE_CONTROL_INOPERATIONSTATE_H
#define PRODUCTION_LINE_CONTROL_INOPERATIONSTATE_H

class InOperationState {

};

#endif //PRODUCTION_LINE_CONTROL_INOPERATIONSTATE_H
